services:
  - type: web
    name: getagro-site
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application --access-logfile - --error-logfile - --log-level info --capture-output
    envVars:
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ""
      - key: CSRF_TRUSTED_ORIGINS
        value: ""
      - key: DEFAULT_FROM_EMAIL
        value: "no-reply@getagro.site"
      - key: CONTACT_TO_EMAIL
        value: "douglasherzog@gmail.com"
      - key: WHATSAPP_URL
        value: ""
      - key: DATABASE_URL
        fromDatabase:
          name: getagro-db
          property: connectionString

databases:
  - name: getagro-db
    plan: free
    databaseName: getagro
    user: getagro
